#!/bin/sh
# (C) 2013,2022 Canonical Ltd.
# (C) 2019 Simon McVittie
# Authors: Iain Lane, Sebastien Bacher, Simon McVittie
# SPDX-License-Identifier: LGPL-2.0-or-later

set -eu

export G_MESSAGES_DEBUG=all
export XDG_RUNTIME_DIR="$AUTOPKGTEST_TMP"


printf "Running as: "; id -a
printf "passwd entry: "; getent passwd "$(id -u)" || echo "(exit status $?)"
printf "group entry: "; getent group "$(id -g)" || echo "(exit status $?)"
echo "Environment:"
env | LC_ALL=C sort -u

exec dbus-run-session -- xvfb-run -a gnome-desktop-testing-runner gtksourceview-4
