.\" Copyright (C) 2020 Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH cafe-time-admin 1 "2020\-02\-14" "CAFE"
.SH "NAME"
\fBcafe-time-admin\fR \- set date and time
.SH "SYNOPSIS"
.B cafe-time-admin
.RI [ OPTIONS... ]
.SH "DESCRIPTION"
This executable is part of the package 'cafe\-control\-center': The CAFE Control Center.
.PP
Use \fBcafe\-time\-admin\fR
, the CAFE Time Admin Tool, to set date and time of the local system.
.SH AUTHORS
This manual page was writtenby Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
for the Debian project (but may be used by others).
.SH OPTIONS
This program accepts the standard CAFE and GTK options.
.SH "SEE ALSO"
Latest version of the CAFE Desktop User Guide for your platform.
.PP
.BR "cafe-control-center" (1),
.BR "caja" (1),
.BR "gtk-options" (7)
