#! /usr/bin/dh-exec

usr/lib/*/cafe-sensors-applet/plugins/libacpi.so
usr/lib/*/cafe-sensors-applet/plugins/libhddtemp.so
usr/lib/*/cafe-sensors-applet/plugins/libi8k.so
usr/lib/*/cafe-sensors-applet/plugins/libibm-acpi.so
usr/lib/*/cafe-sensors-applet/plugins/libmbmon.so
usr/lib/*/cafe-sensors-applet/plugins/libomnibook.so
usr/lib/*/cafe-sensors-applet/plugins/libpmu-sys.so
usr/lib/*/cafe-sensors-applet/plugins/libsmu-sys.so
usr/lib/*/cafe-sensors-applet/plugins/libsonypi.so
[linux-any] usr/lib/*/cafe-sensors-applet/plugins/liblibsensors.so
usr/lib/*/cafe-sensors-applet/plugins/libudisks*.so
[kfreebsd-any hurd-any] usr/lib/*/cafe-sensors-applet/plugins/libi2c-proc.so
[kfreebsd-any hurd-any] usr/lib/*/cafe-sensors-applet/plugins/libi2c-sys.so
usr/lib/cafe-sensors-applet/
usr/share/dbus-1/
usr/share/cafe-panel/applets/
