#! /bin/sh
set -e

write_cache()
{
if [ -x `which ctk-update-icon-cache` ]; then
    if ! ctk-update-icon-cache --force --quiet /usr/share/icons/cafe; then
        echo "WARNING: icon cache generation failed"
    fi
fi
}

if [ "$1" = "triggered" ]; then
    write_cache
    exit 0
fi

write_cache

#DEBHELPER#
