#!/bin/sh

set -eux

cd "$AUTOPKGTEST_TMP"

if [ -n "${DEB_HOST_GNU_TYPE:-}" ]; then
    CROSS_COMPILE="$DEB_HOST_GNU_TYPE-"
else
    CROSS_COMPILE=
fi

cat > bean.c <<'EOF'
#include <glib-object.h>
#include <libbean/bean.h>

int main (int argc, char *argv[])
{
    PeasEngine *engine = bean_engine_new ();

    g_assert_nonnull (engine);
    bean_engine_enable_loader (engine, "python3");
    g_object_unref (engine);
    return 0;
}
EOF

# Deliberately word-splitting, that's how pkg-config works:
# shellcheck disable=SC2046
"${CROSS_COMPILE}gcc" -o bean bean.c $("${CROSS_COMPILE}pkg-config" --cflags --libs libbean-1.0)
test -x bean
G_DEBUG=fatal_warnings,fatal_criticals ./bean

cat > gtk.c <<'EOF'
#include <glib-object.h>
#include <libbean-gtk/bean-gtk.h>

int main (int argc, char *argv[])
{
    GType type = bean_gtk_plugin_manager_get_type ();

    g_assert_cmpuint (type, !=, G_TYPE_INVALID);
    return 0;
}
EOF

# shellcheck disable=SC2046
"${CROSS_COMPILE}gcc" -o gtk gtk.c $("${CROSS_COMPILE}pkg-config" --cflags --libs libbean-gtk-1.0)
test -x gtk
G_DEBUG=fatal_warnings,fatal_criticals ./gtk

echo "# everything seems OK"
